### ISSUE TITLE
Support games detection before first start

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/ME3TweaksModManager#179]
**Is your feature request related to a problem? Please describe.**
As I had already hinted on discord some months ago, it should be possible to programmatically detect where the game is installed, even though the user hasn't started it yet once, or in other words without the help of `HKLM\SOFTWARE\bioware`
(I'm opening the issue here, but I guess like ALOTInstaller and whatnots would also appreciate)

**Describe the solution you'd like**
Steam writes the uninstaller entry as soon as you say that you want to download the game, i.e.:

    HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 17460

Origin is a bit more refined. 
While download is in progress, the only place where the game path is stored is the URI query "dipInstallPath" inside

    %ALLUSERSPROFILE%\Origin\LocalContent\Mass Effect\OFB-EAST55465.mfst

(but not that we should care about that). Once the \*automatic\* installation happens at the end of the download, you get all:

    %ALLUSERSPROFILE%\Origin\LocalContent\Mass Effect\OFB-EAST55465.dat
    HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\GameUX\Games\{9DAC55A6-9EE2-40DB-8F85-E510517889FA}
    HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{44A570EE-FD93-4086-8997-2C38DFDE0019}

To be absolutely clear, I made sure all those places were clean before every download attempt

**Describe alternatives you've considered**
Mgamerz said this wasn't possible because nonetheless, such data was getting written on the "first launch" of the game in steam/origin. 
I tested both and this wasn't the case. I guess there is also retail, let alone ME2 and ME3, but I'm confident behavior would be similar. 

**Additional context**
Goddamit, I just discovered origin installation forces itself the WINXPSP3 and RUNASADMIN flags on ME1 (and also firewall entries because reasons)
I'm wondering if it was actually EA then, to ask microsoft for inclusion of the infamous RunAsHighest shim. 
Also TIL the GDFBinary dlls are "game definition files".

**Comment by mirh** [comment]
Not sure why that should be much of a concern.. 
I understand "stupidity as no limits", but I refuse to believe that even a monkey would try to.. *do stuff* on a game not yet even installed? Why not complaining it ain't working when you didn't even buy it at this point...

*Anyhow*, it's true that steam preallocates stuff and all. But until download has ended `Steamapps\common\Mass Effect` is completely empty. All "temporary" files are getting stored in `Steamapps\downloading\17460`. 
Another way could be to check `appmanifest_17460.acf`. Long story short, I found these entries to be halfway reliable:

* StateFlags: it should be "4", but I'm not sure what [could happen](https://www.reddit.com/r/Steam/comments/5zxn9d/how_to_skip_updates_for_appsgames_installed_via/) if the repair function was triggered
* SizeOnDisk: I personally have "13327828998", but I'd rather just check for "different from zero"
* buildid: [2794](https://steamdb.info/app/17460/depots/#depots-raw)
* InstalledDepots: I guess you could even check this array to be populated with two entries

Note that `HKCU\Software\Valve\Steam\Apps\17460` is sort of a red herring. The *Installed* DWORD is set when you "request the installation" (as you'd expect), but *Updating* can become 0 (with the key undistinguishable from an actually fully installed game) even just if you pause the download. 

---
As for the OFB, I didn't really know which other IDs there may be (the south american and eastern europe editions maybe?).. But whatever they are, they'll always be inside the `LocalContent\Mass Effect` folder. 
Also, you don't really have to look there. 
To uniform with steam you could just simply look at their relative Windows uninstall registry entries (string *InstallLocation*).

**Comment by Mgamerz** [comment]
> I understand "stupidity as no limits", but I refuse to believe that even a monkey would try to.. do stuff on a game not yet even installed

You have no idea the type of users I deal with 😂

**Comment by mirh** [comment]
Steam's `installscript.vdf` will:

* set `HKLM\SOFTWARE\Wow6432Node\Electronic Arts\Electronic Arts\Mass Effect (tm)\ergc` with the cd key
* set `HKLM\SOFTWARE\Wow6432Node\bioware\mass effect` with the game *path* and *flavour*
* run DXSetup 
* run VC80_Redist

If you try to start MassEffect.exe directly you'll get "Application load error 5:0000065434" from the steam stub drm, all shortcuts to the game must be `steam://rungameid/17460`. 
I'm not sure how or why (even if this was the case) it should be "you" to be running/launching the game. 

First run status can also be checked in `HKCU\Software\Valve\Steam\Apps\17460` (or you could cut the middleman and just try to check if you can load `msvcp80.dll` and `d3dx9_31.dll`)

**Comment by Mgamerz** [comment]
Interesting on the application load error. I have some users who get this but I never knew why, also cause I don't have steam versions of these games. Is that only for first run or always?

**Comment by mirh** [comment]
I don't have ME2 on steam, but anyway that error is always supposed to happen (at least unless you create file `steam_appid.txt`)
https://www.pcgamingwiki.com/wiki/User:Cyanic/Steam_DRM#Examples

**Comment by Mgamerz** [comment]
Seems like they could have, you know, put a useful error message or something...

**Comment by mirh** [comment]
Well, they *at least* put an error message returning codes in the first place, so there's that..
I'm not sure for that 65432 offset, anyhow that should mean `ERROR_FILE_NOT_FOUND` (`Steam.dll` I think).

**Comment by mirh** [comment]
Ok, I also figured out why some people can launch directly from the exe even without the txt file, and why others may not be able to launch the thing *even with the txt file*. 

It's not some steam dll that the error message is complaining about. It's `steam.exe`. 
If you don't launch the games from inside steam, the DRM will nonetheless try to find it on its own. Only the gods know why they can't look for the thing properly inside the registry, because they are just recursively looking for it backwards from the game path. 
In other words, if your \<game-folder> is a contained within the steam application folder, `steam.exe -applaunch 17460` is invoked and everything proceeds as usual. 
If your game is installed somewhere else (including, but not limited to, another disk for example) it will fail. 

***If*** you provide `steam_appid.txt` though, and only ***if*** the steam client is running, through the dll they load from `HKCU\Software\Valve\Steam\ActiveProcess\SteamClientDll`, they'll be able to trigger the right DRM code to unlock the launch and all.

**Comment by Mgamerz** [comment]
Can you show me the contents of `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 17460` ? Is there a version of this for ME2? (I don't have either of these games on Steam)

**Comment by mirh** [comment]
https://docs.microsoft.com/en-us/windows/win32/msi/uninstall-registry-key
It's an entirely standardized thing. 
![reg](https://user-images.githubusercontent.com/9366725/102698007-b6f55580-423a-11eb-900e-1ce8fd8ced04.png)
I don't have ME2 on steam either, but clearly the only difference should just be that you look for app id 24980 rather than 17460.

**Comment by Mgamerz** [comment]
Thanks for the research on this. I've just implemented this into my local code after purchasing the games on steam. I installed ME1 and paused ME2 during install for testing, since steam doesn't move any files into the game directory until it finishes downloading, there's not really any need to worry about half downloaded games, as the sanity checks I have for target loading will make the target not load since the files aren't there.

Mod Manager will still give preferential treatment to the main registry keys as the active game. If there is no active game (or it's invalid), the steam lookup will take over as active (I'm not sure it should... maybe should always be inactive, so switching works properly... hmmm, will have to research internal M3 behavior more). If there is an active registry target already (that's different), steam versions will show up as additional targets.

**Comment by mirh** [comment]
Steam just knows where its library folders are (`<steam-folder>\SteamApps\libraryfolders.vdf`), then it just opens them and parses the .acf files. 
Launch parameters and such are stored in `<steam-folder>\appcache\appinfo.vdf`
It has no uses for the uninstall entries, which are just for.. well, uninstall (I mean, maybe also its own, but it's probably mainly for Windows)

You are still missing out Origin though.

**Comment by Mgamerz** [comment]
Origin writes the location of the game it will boot to the bioware keys before first launch. So if those keys are missing, the game is not yet installed, or is installed wrong. If the path is valid, origin will run the game, even if it isn't using origin drm. Mod Manager writes a list of all games it's found as modding targets which means it will be subsequently picked up for modding.

**Comment by mirh** [comment]
Are you sure? There's no such a thing into ME2's _installerdata.xml_.

**Comment by Mgamerz** [comment]
So am testing it for ME2 on Origin. I already had it installed in origin so I just went into regedit and nuked SOFTWARE/WOW6432Node/BioWare/Mass Effect 2, which would cause Origin to not think the game is installed (nor modding tools that look for it there). Simple enough right?

Origin no longer thought the game was installed, and I pressed install in Origin. After waiting for an eternity for it to 'prepare', and some monitoring with ProcMon, Origin found the game in the default library directory. It seems like it has some sort of autodetection of games in the default game library folder? Cause it immediately tried to repair the game instead of asking me to download it fresh. I restarted origin but when I clicked install next time, it asked me to download it instead.

I pointed it at a new directory, and now it won't even install. Origin downloads the basegame, and then tries to access the aforementioned registry key. It doesn't exist (because I deleted it - just like the uninstaller would do!) and it throws an error instead. I don't really understand how this is possible, because at no point has the origin game installer tried to write to this key from what I can see. It's tried to access it a lot (it does it all the time) but at this point it hits it hundreds of times, always fails, and then gives up. It thinks the game is installed in the game library but none of the DLC will install and it always says download failed. It seems like at this point it should be writing the key but instead it's just not doing that.

I created the key and it still doesn't work, it's trying to access some values like InstallDir, which obviously never were set. It's behaving like it thinks the keys should already be there, which they aren't, because I'm installing the game fresh. I don't know if this is just some bad design in the Origin app or if it's them seeing the game in the game library folder, and incorrectly assuming the keys should already be there. Maybe Origin has some built in cache of where it thinks the game is installed - maybe it just assumes if the uninstall entry is there, the keys are there? Seems really weird the installer would assume something like that.

Anyways now I get to try and fix the problem with my local copy of Origin. I've already filed a bug report (given their release notes, and pace of fixing things, I expect this will never be fixed).

**Comment by Mgamerz** [comment]
The uninstaller shows the following log:

```
00:33:33  Initialized installation config.
00:33:33  CommandLine: uninstall_game -autologging
00:33:33  OS: Microsoft Windows 8 Professional
00:33:33  Data reader initialized.
00:33:33  Data reader config: LOCALE = en_US
00:33:33  Data reader config: 32BIT = 0
00:33:33  Data reader config: 64BIT = 1
00:33:33  Processing EAIN file 'C:\Program Files (x86)\Common Files\EAInstaller\Mass Effect 2\Cleanup.dat'.
00:33:33  Installation registry missing.  Game not yet installed.
00:33:33  (Config)Studio: BioWare
00:33:33  (Config)Game Name: Mass Effect 2
00:33:33  (Config)Display Game Name: Mass Effect™ 2
00:33:33  (Config)Updating ForceUninstallAllFiles to: 0
00:33:33  (Config)Updating ForceUninstallAllFiles to: 1
00:33:33  Showing uninstall confirmation dialog ... 
00:33:34  User confirmed uninstall ... 
00:33:34  Show uninstall progress dialog ... 
00:33:35  Unable to retrieve installed location from registry ... 
00:33:35  Checking if game is running ...
00:33:47  Checking if game dependent exe is running ...
00:33:47  Start dependencies cleanup phase
00:33:47  End of dependencies cleanup phase
00:33:47  Uninstalling GDF ...
00:33:47  Retrieving GDF dll path from \\HLKM\Software\BioWare\Mass Effect 2\GDFBinary ...
00:33:47  Unable to retrieve GDF dll path from \\HLKM\Software\BioWare\Mass Effect 2\GDFBinary64 ...
00:33:47  The installed DLL has been removed.  Attempting to use backup GDF DLL.
00:33:47  Using backup GDF DLL.
00:33:47  Removing shortcuts ...
00:33:47  Uninstall finished with exit code: 1
00:33:47  Shutting down data reader.

****************************************
```

Curious how it says it was removed. The uninstall entries are not removed, nor is the cleanup files. It's like the uninstaller does nothing.

**Comment by Mgamerz** [comment]
It looks like Origin really tries to prefer the local main library folder. I tried downloading it again and it keeps trying to use the folder that already exists. I just entirely nuked it and will see if it works. It looks like if the game exists in the library, it will fubar a lot of things in Origin, like making it think the game is already installed and configured when it's not. Might be some edge cases they did not code for when they started allowing install outside of the library folder years ago.

**Comment by Mgamerz** [comment]
Removing the game from my local library fixed it. It looks like it sees game in local game library folder, and assumes it's correctly installed, which is a bad assumption to make. Might be an error in the EAInstaller code the game uses however. The registry keys are set during this so we don't need to worry about origin not installing the keys. Curiously the installer is looking for steam files like installScript.vdf.

**Comment by Mgamerz** [comment]
Found some real interesting stuff. Took a whack at reverse engineering the touchup.dat file. Fed touchup.exe through IDA and after about an hour of analysis (and me not figuring how to bring up the python console in IDA, if there even is one), I was able to produce a decompiled script for it.

Touchup.dat, at least for ME2, is a 'encrypted' file that is just xored on all bytes with the cipher 0x0B4 on all bytes.

![image](https://user-images.githubusercontent.com/2738836/103148183-5ecac180-471a-11eb-93b7-4a6ac12ff442.png)

The resulting data after xoring starts with 'LuaQ', which appears to be a Lua 5.1 compiled file. I attached the binary data below. It is E0F0 in length.

[me2touchuplua.zip](https://github.com/ME3Tweaks/ME3TweaksModManager/files/5742855/me2touchuplua.zip)

After feeding this trhough 'luadec51_2.0.2', I was able to produce the follow decompiled script output (note this is output from the decompile program, not the script itself):

[me2touchuplua.txt](https://github.com/ME3Tweaks/ME3TweaksModManager/files/5742848/me2touchuplua.txt)

Some of the parts of the script include setting the registry keys for the game. I might just take a crack at making a small automated program, just so we can see what other touchup files do for ME1 and 3. I'm sure there's nothing interesting but I'm curious now.

**Comment by mirh** [comment]
It's not that origin has some magical auto-detection (or if not any, I don't think that's the deal here). 
You simply have the game folders path hard-coded in the `*.dat` files in programdata. That's what it looks for first and foremost AFAIK, and that's also why changing folders is a bit of a glitchy mess. I had to use a hex editor to rename Apex Legends's folder for example. 

Though I didn't know they were also checking for the "STUDIO" registry entries (I thought only the games themselves or DLCs cared) and most definitively I didn't know _touchup.exe_ came with a plethora of built-in commands. 
GG. 
Would be nice if you could have the excuse to create "origin tools" and resurrect PAREditor /s

**Comment by mirh** [comment]
Duh.. though with respect to detecting the games, I think we are already done then?
