### ISSUE TITLE
Feature request: Unbind console keys

### ISSUE THREAD

**Issue by levicki** [ME3Tweaks/ME3TweaksModManager#323]
**Steps to reproduce:**
1. Open Console Key Keybinder
![image](https://user-images.githubusercontent.com/16415478/193432728-dfaa8907-8891-4cdb-8741-1af066698898.png)
2. Click on Change full key or Change mini key button **for an installed game which has no backup**, you will get this prompt
![image](https://user-images.githubusercontent.com/16415478/193432753-b4d5d21a-bfdd-4517-9b5d-4a27fa44a607.png)

**Expected behavior:**
 - Clicking Yes should allow you to change the key binding

**Actual behavior:**
 - Clicking Yes does nothing, while clicking No allows you to change key binding

While we are at it, it would be nice if each key could be cleared (unassigned). If it is already possible it is not immediately obviousl.

**Comment by Mgamerz** [comment]
I just fixed this in my current code, sorry for not replying, somehow missed this. Unbinding a single key isn't possible right now, but I can look into making it completely unbind it - not sure when I'll get to it.

**Comment by levicki** [comment]
@Mgamerz No problem, happy New Year.

**Comment by Mgamerz** [comment]
The bugfix is available now in 8.0.1; however I'm keeping this open and changing the title for the feature request part.

**Comment by levicki** [comment]
@Mgamerz Would you like me to open a separate issue for feature request so you can close this one?

**Comment by levicki** [comment]
@Mgamerz This isn't fully fixed -- you forgot to fix the Change mini key button message box, it is still reversed.

**Comment by Mgamerz** [comment]
This was resolved in the March 18, 2023 build of 8.0.1. The unbind feature was also implemented.
